//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BinaryStudio.PlatformUI.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BinaryStudio.PlatformUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error_ConverterFunctionNotDefined.
        /// </summary>
        public static string Error_ConverterFunctionNotDefined {
            get {
                return ResourceManager.GetString("Error_ConverterFunctionNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error_InsufficientSourceParameters.
        /// </summary>
        public static string Error_InsufficientSourceParameters {
            get {
                return ResourceManager.GetString("Error_InsufficientSourceParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error_InsufficientTypeParameters.
        /// </summary>
        public static string Error_InsufficientTypeParameters {
            get {
                return ResourceManager.GetString("Error_InsufficientTypeParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error_TargetAtOffsetNotExtendingType.
        /// </summary>
        public static string Error_TargetAtOffsetNotExtendingType {
            get {
                return ResourceManager.GetString("Error_TargetAtOffsetNotExtendingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error_TargetNotExtendingType.
        /// </summary>
        public static string Error_TargetNotExtendingType {
            get {
                return ResourceManager.GetString("Error_TargetNotExtendingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error_ValueAtOffsetNotOfType.
        /// </summary>
        public static string Error_ValueAtOffsetNotOfType {
            get {
                return ResourceManager.GetString("Error_ValueAtOffsetNotOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error_ValueNotOfType.
        /// </summary>
        public static string Error_ValueNotOfType {
            get {
                return ResourceManager.GetString("Error_ValueNotOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Offset.
        /// </summary>
        public static string HexBox_Offset {
            get {
                return ResourceManager.GetString("HexBox.Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на NormalizeError_InvalidPathChar2.
        /// </summary>
        public static string NormalizeError_InvalidPathChar {
            get {
                return ResourceManager.GetString("NormalizeError_InvalidPathChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ProcessPriorityClass_AboveNormal.
        /// </summary>
        public static string ProcessPriorityClass_AboveNormal {
            get {
                return ResourceManager.GetString("ProcessPriorityClass_AboveNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ProcessPriorityClass_BelowNormal.
        /// </summary>
        public static string ProcessPriorityClass_BelowNormal {
            get {
                return ResourceManager.GetString("ProcessPriorityClass_BelowNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ProcessPriorityClass_High.
        /// </summary>
        public static string ProcessPriorityClass_High {
            get {
                return ResourceManager.GetString("ProcessPriorityClass_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ProcessPriorityClass_Idle.
        /// </summary>
        public static string ProcessPriorityClass_Idle {
            get {
                return ResourceManager.GetString("ProcessPriorityClass_Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ProcessPriorityClass_NA.
        /// </summary>
        public static string ProcessPriorityClass_NA {
            get {
                return ResourceManager.GetString("ProcessPriorityClass_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ProcessPriorityClass_Normal.
        /// </summary>
        public static string ProcessPriorityClass_Normal {
            get {
                return ResourceManager.GetString("ProcessPriorityClass_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ProcessPriorityClass_RealTime.
        /// </summary>
        public static string ProcessPriorityClass_RealTime {
            get {
                return ResourceManager.GetString("ProcessPriorityClass_RealTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Property.
        /// </summary>
        public static string PropertyGridControl_Field {
            get {
                return ResourceManager.GetString("PropertyGridControl.Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Value.
        /// </summary>
        public static string PropertyGridControl_Value {
            get {
                return ResourceManager.GetString("PropertyGridControl.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Services_InvokedOnWrongThread.
        /// </summary>
        public static string Services_InvokedOnWrongThread {
            get {
                return ResourceManager.GetString("Services_InvokedOnWrongThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ThreadHelper_UIThreadDispatcherUnavailable.
        /// </summary>
        public static string ThreadHelper_UIThreadDispatcherUnavailable {
            get {
                return ResourceManager.GetString("ThreadHelper_UIThreadDispatcherUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ValidateError_GuidEmpty.
        /// </summary>
        public static string ValidateError_GuidEmpty {
            get {
                return ResourceManager.GetString("ValidateError_GuidEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ValidateError_InvalidOperation.
        /// </summary>
        public static string ValidateError_InvalidOperation {
            get {
                return ResourceManager.GetString("ValidateError_InvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ValidateError_InvalidValue_Format.
        /// </summary>
        public static string ValidateError_InvalidValue_Format {
            get {
                return ResourceManager.GetString("ValidateError_InvalidValue_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ValidateError_OutOfRange_Format.
        /// </summary>
        public static string ValidateError_OutOfRange_Format {
            get {
                return ResourceManager.GetString("ValidateError_OutOfRange_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ValidateError_PathNotNormalized_Format.
        /// </summary>
        public static string ValidateError_PathNotNormalized_Format {
            get {
                return ResourceManager.GetString("ValidateError_PathNotNormalized_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ValidateError_StringEmpty.
        /// </summary>
        public static string ValidateError_StringEmpty {
            get {
                return ResourceManager.GetString("ValidateError_StringEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ValidateError_StringWhiteSpace.
        /// </summary>
        public static string ValidateError_StringWhiteSpace {
            get {
                return ResourceManager.GetString("ValidateError_StringWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ValidateError_UnexpectedValue_Format.
        /// </summary>
        public static string ValidateError_UnexpectedValue_Format {
            get {
                return ResourceManager.GetString("ValidateError_UnexpectedValue_Format", resourceCulture);
            }
        }
    }
}
