//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BinaryStudio.Security.Cryptography.Interchange
{
    using System;
    using System.Collections.Generic;
    
    public partial class DGeneralName
    {
        public DGeneralName()
        {
            this.AlternativeName = new HashSet<DAlternativeName>();
            this.AuthorityKeyIdentifier = new HashSet<DAuthorityKeyIdentifier>();
        }
    
        public int GeneralNameId { get; set; }
        public byte Type { get; set; }
        public string Value { get; set; }
    
        public virtual ICollection<DAlternativeName> AlternativeName { get; set; }
        public virtual ICollection<DAuthorityKeyIdentifier> AuthorityKeyIdentifier { get; set; }
        public virtual DRelativeDistinguishedNameSequence RelativeDistinguishedNameSequence { get; set; }
    }
}
