//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BinaryStudio.Security.Cryptography.Interchange
{
    using System;
    using System.Collections.Generic;
    
    public partial class DObjectIdentifier
    {
        public DObjectIdentifier()
        {
            this.Extension = new HashSet<DExtension>();
            this.RelativeDistinguishedName = new HashSet<DRelativeDistinguishedName>();
        }
    
        public int Id { get; set; }
        public string Value { get; set; }
        public string ShortName { get; set; }
    
        public virtual ICollection<DExtension> Extension { get; set; }
        public virtual ICollection<DRelativeDistinguishedName> RelativeDistinguishedName { get; set; }
    }
}
