//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BinaryStudio.Security.Cryptography.Interchange
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRelativeDistinguishedNameSequence
    {
        public DRelativeDistinguishedNameSequence()
        {
            this.Certificate = new HashSet<DCertificate>();
            this.Certificate1 = new HashSet<DCertificate>();
            this.CertificateRevocationList = new HashSet<DCertificateRevocationList>();
            this.RelativeDistinguishedNameSequenceMapping = new HashSet<DRelativeDistinguishedNameSequenceMapping>();
        }
    
        public int RelativeDistinguishedNameSequenceId { get; set; }
    
        public virtual ICollection<DCertificate> Certificate { get; set; }
        public virtual ICollection<DCertificate> Certificate1 { get; set; }
        public virtual ICollection<DCertificateRevocationList> CertificateRevocationList { get; set; }
        public virtual DGeneralName GeneralName { get; set; }
        public virtual ICollection<DRelativeDistinguishedNameSequenceMapping> RelativeDistinguishedNameSequenceMapping { get; set; }
    }
}
