//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BinaryStudio.Security.Cryptography.AbstractSyntaxNotation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BinaryStudio.Security.Cryptography.AbstractSyntaxNotation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container.
        /// </summary>
        internal static string _9000 {
            get {
                return ResourceManager.GetString("9000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string _9001 {
            get {
                return ResourceManager.GetString("9001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asn1CertificateAuthorityInformationAccess:0.
        /// </summary>
        internal static string Asn1CertificateAuthorityInformationAccess_0 {
            get {
                return ResourceManager.GetString("Asn1CertificateAuthorityInformationAccess:0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFC822 Name.
        /// </summary>
        internal static string Asn1CertificateAuthorityInformationAccess_1 {
            get {
                return ResourceManager.GetString("Asn1CertificateAuthorityInformationAccess:1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNS Name.
        /// </summary>
        internal static string Asn1CertificateAuthorityInformationAccess_2 {
            get {
                return ResourceManager.GetString("Asn1CertificateAuthorityInformationAccess:2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asn1CertificateAuthorityInformationAccess:3.
        /// </summary>
        internal static string Asn1CertificateAuthorityInformationAccess_3 {
            get {
                return ResourceManager.GetString("Asn1CertificateAuthorityInformationAccess:3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Address.
        /// </summary>
        internal static string Asn1CertificateAuthorityInformationAccess_4 {
            get {
                return ResourceManager.GetString("Asn1CertificateAuthorityInformationAccess:4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asn1CertificateAuthorityInformationAccess:5.
        /// </summary>
        internal static string Asn1CertificateAuthorityInformationAccess_5 {
            get {
                return ResourceManager.GetString("Asn1CertificateAuthorityInformationAccess:5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniform Resource Identifier.
        /// </summary>
        internal static string Asn1CertificateAuthorityInformationAccess_6 {
            get {
                return ResourceManager.GetString("Asn1CertificateAuthorityInformationAccess:6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asn1CertificateAuthorityInformationAccess:7.
        /// </summary>
        internal static string Asn1CertificateAuthorityInformationAccess_7 {
            get {
                return ResourceManager.GetString("Asn1CertificateAuthorityInformationAccess:7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asn1CertificateAuthorityInformationAccess:8.
        /// </summary>
        internal static string Asn1CertificateAuthorityInformationAccess_8 {
            get {
                return ResourceManager.GetString("Asn1CertificateAuthorityInformationAccess:8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Method.
        /// </summary>
        internal static string Asn1CertificateAuthorityInformationAccess_AccessMethod {
            get {
                return ResourceManager.GetString("Asn1CertificateAuthorityInformationAccess.AccessMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Method.
        /// </summary>
        internal static string Asn1CertificateAuthorityInformationAccessExtension_AccessMethod {
            get {
                return ResourceManager.GetString("Asn1CertificateAuthorityInformationAccessExtension.AccessMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Issuer.
        /// </summary>
        internal static string Asn1CertificateAuthorityKeyIdentifierExtension_CertificateIssuer {
            get {
                return ResourceManager.GetString("Asn1CertificateAuthorityKeyIdentifierExtension.CertificateIssuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Identifier.
        /// </summary>
        internal static string Asn1CertificateAuthorityKeyIdentifierExtension_KeyIdentifier {
            get {
                return ResourceManager.GetString("Asn1CertificateAuthorityKeyIdentifierExtension.KeyIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial number.
        /// </summary>
        internal static string Asn1CertificateAuthorityKeyIdentifierExtension_SerialNumber {
            get {
                return ResourceManager.GetString("Asn1CertificateAuthorityKeyIdentifierExtension.SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path Length Constraint.
        /// </summary>
        internal static string Asn1CertificateBasicConstraintsExtension_PathLengthConstraint {
            get {
                return ResourceManager.GetString("Asn1CertificateBasicConstraintsExtension.PathLengthConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject Type.
        /// </summary>
        internal static string Asn1CertificateBasicConstraintsExtension_SubjectType {
            get {
                return ResourceManager.GetString("Asn1CertificateBasicConstraintsExtension.SubjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        internal static string Asn1CertificateExtension_Identifier {
            get {
                return ResourceManager.GetString("Asn1CertificateExtension.Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsCritical.
        /// </summary>
        internal static string Asn1CertificateExtension_IsCritical {
            get {
                return ResourceManager.GetString("Asn1CertificateExtension.IsCritical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certification Authority descriptive name.
        /// </summary>
        internal static string Asn1CertificateIssuerDigitalSigningToolExtension_CertificationAuthorityDescriptiveName {
            get {
                return ResourceManager.GetString("Asn1CertificateIssuerDigitalSigningToolExtension.CertificationAuthorityDescriptiv" +
                        "eName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conformity properties of Certification Authority.
        /// </summary>
        internal static string Asn1CertificateIssuerDigitalSigningToolExtension_ConformityPropertiesOfCertificationAuthority {
            get {
                return ResourceManager.GetString("Asn1CertificateIssuerDigitalSigningToolExtension.ConformityPropertiesOfCertificat" +
                        "ionAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conformity properties of software used to create digital signature.
        /// </summary>
        internal static string Asn1CertificateIssuerDigitalSigningToolExtension_ConformityPropertiesOfSoftwareUsedToCreateDigitalSignature {
            get {
                return ResourceManager.GetString("Asn1CertificateIssuerDigitalSigningToolExtension.ConformityPropertiesOfSoftwareUs" +
                        "edToCreateDigitalSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software used to create digital signature.
        /// </summary>
        internal static string Asn1CertificateIssuerDigitalSigningToolExtension_SoftwareUsedToCreateDigitalSignature {
            get {
                return ResourceManager.GetString("Asn1CertificateIssuerDigitalSigningToolExtension.SoftwareUsedToCreateDigitalSigna" +
                        "ture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid from.
        /// </summary>
        internal static string Asn1CertificatePrivateKeyUsagePeriodExtension_NotAfter {
            get {
                return ResourceManager.GetString("Asn1CertificatePrivateKeyUsagePeriodExtension.NotAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid to.
        /// </summary>
        internal static string Asn1CertificatePrivateKeyUsagePeriodExtension_NotBefore {
            get {
                return ResourceManager.GetString("Asn1CertificatePrivateKeyUsagePeriodExtension.NotBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Identifier.
        /// </summary>
        internal static string Asn1CertificateSubjectKeyIdentifierExtension_Value {
            get {
                return ResourceManager.GetString("Asn1CertificateSubjectKeyIdentifierExtension.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string Boolean_False {
            get {
                return ResourceManager.GetString("Boolean.False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string Boolean_True {
            get {
                return ResourceManager.GetString("Boolean.True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CrlSign.
        /// </summary>
        internal static string X509KeyUsageFlags_CrlSign {
            get {
                return ResourceManager.GetString("X509KeyUsageFlags.CrlSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Encipherment.
        /// </summary>
        internal static string X509KeyUsageFlags_DataEncipherment {
            get {
                return ResourceManager.GetString("X509KeyUsageFlags.DataEncipherment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decipher Only.
        /// </summary>
        internal static string X509KeyUsageFlags_DecipherOnly {
            get {
                return ResourceManager.GetString("X509KeyUsageFlags.DecipherOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Signature.
        /// </summary>
        internal static string X509KeyUsageFlags_DigitalSignature {
            get {
                return ResourceManager.GetString("X509KeyUsageFlags.DigitalSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encipher Only.
        /// </summary>
        internal static string X509KeyUsageFlags_EncipherOnly {
            get {
                return ResourceManager.GetString("X509KeyUsageFlags.EncipherOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Agreement.
        /// </summary>
        internal static string X509KeyUsageFlags_KeyAgreement {
            get {
                return ResourceManager.GetString("X509KeyUsageFlags.KeyAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyCertSign.
        /// </summary>
        internal static string X509KeyUsageFlags_KeyCertSign {
            get {
                return ResourceManager.GetString("X509KeyUsageFlags.KeyCertSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Encipherment.
        /// </summary>
        internal static string X509KeyUsageFlags_KeyEncipherment {
            get {
                return ResourceManager.GetString("X509KeyUsageFlags.KeyEncipherment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Repudiation.
        /// </summary>
        internal static string X509KeyUsageFlags_NonRepudiation {
            get {
                return ResourceManager.GetString("X509KeyUsageFlags.NonRepudiation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CA.
        /// </summary>
        internal static string X509SubjectType_CA {
            get {
                return ResourceManager.GetString("X509SubjectType.CA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Entity.
        /// </summary>
        internal static string X509SubjectType_EndEntity {
            get {
                return ResourceManager.GetString("X509SubjectType.EndEntity", resourceCulture);
            }
        }
    }
}
