using System;
using System.Diagnostics.CodeAnalysis;

namespace BinaryStudio.Security.Cryptography.CryptographyServiceProvider
    {
    #if CODE_ANALYSIS
    [SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>")]
    #endif
    public static class ObjectIdentifiers
        {
        private const String ISO                        = "1";
        private const String ISOMemberBody              = ISO + ".2";
        private const String ISOIdentifiedOrganization  = ISO + ".3";
        private const String ISOMemberBodyUSA           = ISOMemberBody + ".840";
        private const String RSADSI                     = ISOMemberBodyUSA + ".113549";
        private const String RSADSIPKCS                 = RSADSI + ".1";
        private const String RSADSIHASH                 = RSADSI + ".2";
        private const String RSADSIENC                  = RSADSI + ".3";
        private const String PKCS1                      = RSADSIPKCS + ".1";
        private const String PKCS2                      = RSADSIPKCS + ".2";
        private const String PKCS3                      = RSADSIPKCS + ".3";
        private const String PKCS4                      = RSADSIPKCS + ".4";
        private const String PKCS5                      = RSADSIPKCS + ".5";
        private const String PKCS6                      = RSADSIPKCS + ".6";
        private const String PKCS7                      = RSADSIPKCS + ".7";
        private const String PKCS8                      = RSADSIPKCS + ".8";
        private const String PKCS9                      = RSADSIPKCS + ".9";
        private const String PKCS10                     = RSADSIPKCS + ".10";
        private const String PKCS11                     = RSADSIPKCS + ".11";
        private const String PKCS12                     = RSADSIPKCS + ".12";
        private const String PKCS13                     = RSADSIPKCS + ".13";
        private const String PKCS14                     = RSADSIPKCS + ".14";
        private const String PKCS15                     = RSADSIPKCS + ".15";
        private const String DODNET                     = ISOIdentifiedOrganization + ".6";
        private const String InternetCommunity          = DODNET + ".1";
        private const String InternetSecurity           = InternetCommunity + ".5";
        private const String SecurityMechanism          = InternetSecurity + ".5";
        private const String PKIX                       = SecurityMechanism + ".7";
        public  const String PKIXCertificateExtension   = PKIX + ".1";

        public const String szOID_RSA                                                                          = RSADSI;
        public const String szOID_PKCS                                                                         = RSADSIPKCS;
        public const String szOID_RSA_HASH                                                                     = RSADSIHASH;
        public const String szOID_RSA_ENCRYPT                                                                  = RSADSIENC;
        public const String szOID_PKCS_1                                                                       = PKCS1;
        public const String szOID_RSA_RSA                                                                      = PKCS1 + ".1";
        public const String szOID_RSA_MD2RSA                                                                   = PKCS1 + ".2";
        public const String szOID_RSA_MD4RSA                                                                   = PKCS1 + ".3";
        public const String szOID_RSA_MD5RSA                                                                   = PKCS1 + ".4";
        public const String szOID_RSA_SHA1RSA                                                                  = PKCS1 + ".5";
        public const String szOID_RSA_SETOAEP_RSA                                                              = PKCS1 + ".6";
        public const String szOID_RSAES_OAEP                                                                   = PKCS1 + ".7";
        public const String szOID_RSA_MGF1                                                                     = PKCS1 + ".8";
        public const String szOID_RSA_PSPECIFIED                                                               = PKCS1 + ".9";
        public const String szOID_RSA_SSA_PSS                                                                  = PKCS1 + ".10";
        public const String szOID_RSA_SHA256RSA                                                                = PKCS1 + ".11";
        public const String szOID_RSA_SHA384RSA                                                                = PKCS1 + ".12";
        public const String szOID_RSA_SHA512RSA                                                                = PKCS1 + ".13";
        public const String szOID_PKCS_2                                                                       = PKCS2;
        public const String szOID_PKCS_3                                                                       = PKCS3;
        public const String szOID_RSA_DH                                                                       = PKCS3 + ".1";
        public const String szOID_PKCS_4                                                                       = PKCS4;
        public const String szOID_PKCS_5                                                                       = PKCS5;
        public const String szOID_PKCS_6                                                                       = PKCS6;
        public const String szOID_PKCS_7                                                                       = PKCS7;
        public const String szOID_PKCS_8                                                                       = PKCS8;
        public const String szOID_PKCS_9                                                                       = PKCS9;
        public const String szOID_RSA_emailAddr                                                                = PKCS9 + ".1";
        public const String szOID_RSA_unstructName                                                             = PKCS9 + ".2";
        public const String szOID_RSA_contentType                                                              = PKCS9 + ".3";
        public const String szOID_RSA_messageDigest                                                            = PKCS9 + ".4";
        public const String szOID_RSA_signingTime                                                              = PKCS9 + ".5";
        public const String szOID_RSA_counterSign                                                              = PKCS9 + ".6";
        public const String szOID_RSA_challengePwd                                                             = PKCS9 + ".7";
        public const String szOID_RSA_unstructAddr                                                             = PKCS9 + ".8";
        public const String szOID_RSA_extCertAttrs                                                             = PKCS9 + ".9";
        public const String szOID_RSA_certExtensions                                                           = PKCS9 + ".14";
        public const String szOID_RSA_SMIMECapabilities                                                        = PKCS9 + ".15";
        public const String szOID_RSA_preferSignedData                                                         = szOID_RSA_SMIMECapabilities + ".1";
        private const String SMIME                                                                             = PKCS9 + ".16";
        public const String szOID_TIMESTAMP_TOKEN                                                              = SMIME + ".1.4";
        public const String szCPOID_RSA_SMIMEaaSigningCertificate                                              = SMIME + ".2.12";
        public const String szCPOID_RSA_SMIMEaaSigningCertificateV2                                            = SMIME + ".2.47";
        public const String szCPOID_RSA_SMIMEaaETSotherSigCert                                                 = SMIME + ".2.19";
        public const String szOID_RSA_SMIMEalg                                                                 = SMIME + ".3";
        public const String szOID_RSA_SMIMEalgESDH                                                             = szOID_RSA_SMIMEalg + ".5";
        public const String szOID_RSA_SMIMEalgCMS3DESwrap                                                      = szOID_RSA_SMIMEalg + ".6";
        public const String szOID_RSA_SMIMEalgCMSRC2wrap                                                       = szOID_RSA_SMIMEalg + ".7";
        public const String szOID_PKCS_10                                                                      = PKCS10;
        public const String szOID_PKCS_12                                                                      = PKCS12;
        public const String szOID_RSA_MD2                                                                      = RSADSIHASH + ".2";
        public const String szOID_RSA_MD4                                                                      = RSADSIHASH + ".4";
        public const String szOID_RSA_MD5                                                                      = RSADSIHASH + ".5";
        public const String szOID_RSA_RC2CBC                                                                   = "1.2.840.113549.3.2";
        public const String szOID_RSA_RC4                                                                      = "1.2.840.113549.3.4";
        public const String szOID_RSA_DES_EDE3_CBC                                                             = "1.2.840.113549.3.7";
        public const String szOID_RSA_RC5_CBCPad                                                               = "1.2.840.113549.3.9";
        public const String szOID_X957                                                                         = "1.2.840.10040";
        public const String szOID_X957_DSA                                                                     = "1.2.840.10040.4.1";
        public const String szOID_X957_SHA1DSA                                                                 = "1.2.840.10040.4.3";
        public const String szOID_ANSI_X942                                                                    = "1.2.840.10046";
        public const String szOID_ANSI_X942_DH                                                                 = "1.2.840.10046.2.1";
        public const String szOID_ECC_PUBLIC_KEY                                                               = "1.2.840.10045.2.1";
        public const String szOID_ECC_CURVE_P256                                                               = "1.2.840.10045.3.1.7";
        public const String szOID_ECDSA_SHA1                                                                   = "1.2.840.10045.4.1";
        public const String szOID_ECDSA_SPECIFIED                                                              = "1.2.840.10045.4.3";
        public const String szOID_ECDSA_SHA256                                                                 = "1.2.840.10045.4.3.2";
        public const String szOID_ECDSA_SHA384                                                                 = "1.2.840.10045.4.3.3";
        public const String szOID_ECDSA_SHA512                                                                 = "1.2.840.10045.4.3.4";
        public const String szOID_RFC3161_counterSign                                                          = "1.3.6.1.4.1.311.3.3.1";
        public const String szOID_ECC_CURVE_P384                                                               = "1.3.132.0.34";
        public const String szOID_ECC_CURVE_P521                                                               = "1.3.132.0.35";
        public const String szOID_NIST_AES128_CBC                                                              = "2.16.840.1.101.3.4.1.2";
        public const String szOID_NIST_AES192_CBC                                                              = "2.16.840.1.101.3.4.1.22";
        public const String szOID_NIST_AES256_CBC                                                              = "2.16.840.1.101.3.4.1.42";
        public const String szOID_NIST_AES128_WRAP                                                             = "2.16.840.1.101.3.4.1.5";
        public const String szOID_NIST_AES192_WRAP                                                             = "2.16.840.1.101.3.4.1.25";
        public const String szOID_NIST_AES256_WRAP                                                             = "2.16.840.1.101.3.4.1.45";
        public const String szOID_DH_SINGLE_PASS_STDDH_SHA1_KDF                                                = "1.3.133.16.840.63.0.2";
        public const String szOID_DH_SINGLE_PASS_STDDH_SHA256_KDF                                              = "1.3.132.1.11.1";
        public const String szOID_DH_SINGLE_PASS_STDDH_SHA384_KDF                                              = "1.3.132.1.11.2";
        public const String szOID_DS                                                                           = "2.5";
        public const String szOID_DSALG                                                                        = szOID_DS + ".8";
        public const String szOID_DSALG_CRPT                                                                   = szOID_DSALG + ".1";
        public const String szOID_DSALG_HASH                                                                   = szOID_DSALG + ".2";
        public const String szOID_DSALG_SIGN                                                                   = szOID_DSALG + ".3";
        public const String szOID_DSALG_RSA                                                                    = szOID_DSALG + ".1.1";
        public const String szOID_OIW                                                                          = "1.3.14";
        public const String szOID_OIWSECSIG                                                                    = szOID_OIW + ".3";
        public const String szOID_OIWSEC                                                                       = szOID_OIWSECSIG + ".2";
        public const String szOID_OIWSEC_md4RSA                                                                = szOID_OIWSEC +  ".2";
        public const String szOID_OIWSEC_md5RSA                                                                = szOID_OIWSEC +  ".3";
        public const String szOID_OIWSEC_md4RSA2                                                               = szOID_OIWSEC +  ".4";
        public const String szOID_OIWSEC_desECB                                                                = szOID_OIWSEC +  ".6";
        public const String szOID_OIWSEC_desCBC                                                                = szOID_OIWSEC +  ".7";
        public const String szOID_OIWSEC_desOFB                                                                = szOID_OIWSEC +  ".8";
        public const String szOID_OIWSEC_desCFB                                                                = szOID_OIWSEC +  ".9";
        public const String szOID_OIWSEC_desMAC                                                                = szOID_OIWSEC + ".10";
        public const String szOID_OIWSEC_rsaSign                                                               = szOID_OIWSEC + ".11";
        public const String szOID_OIWSEC_dsa                                                                   = szOID_OIWSEC + ".12";
        public const String szOID_OIWSEC_shaDSA                                                                = szOID_OIWSEC + ".13";
        public const String szOID_OIWSEC_mdc2RSA                                                               = szOID_OIWSEC + ".14";
        public const String szOID_OIWSEC_shaRSA                                                                = szOID_OIWSEC + ".15";
        public const String szOID_OIWSEC_dhCommMod                                                             = szOID_OIWSEC + ".16";
        public const String szOID_OIWSEC_desEDE                                                                = szOID_OIWSEC + ".17";
        public const String szOID_OIWSEC_sha                                                                   = szOID_OIWSEC + ".18";
        public const String szOID_OIWSEC_mdc2                                                                  = szOID_OIWSEC + ".19";
        public const String szOID_OIWSEC_dsaComm                                                               = szOID_OIWSEC + ".20";
        public const String szOID_OIWSEC_dsaCommSHA                                                            = szOID_OIWSEC + ".21";
        public const String szOID_OIWSEC_rsaXchg                                                               = szOID_OIWSEC + ".22";
        public const String szOID_OIWSEC_keyHashSeal                                                           = szOID_OIWSEC + ".23";
        public const String szOID_OIWSEC_md2RSASign                                                            = szOID_OIWSEC + ".24";
        public const String szOID_OIWSEC_md5RSASign                                                            = szOID_OIWSEC + ".25";
        public const String szOID_OIWSEC_sha1                                                                  = szOID_OIWSEC + ".26";
        public const String szOID_OIWSEC_dsaSHA1                                                               = szOID_OIWSEC + ".27";
        public const String szOID_OIWSEC_dsaCommSHA1                                                           = szOID_OIWSEC + ".28";
        public const String szOID_OIWSEC_sha1RSASign                                                           = szOID_OIWSEC + ".29";
        public const String szOID_OIWDIR                                                                       = "1.3.14.7.2";
        public const String szOID_OIWDIR_CRPT                                                                  = szOID_OIWDIR + ".1";
        public const String szOID_OIWDIR_HASH                                                                  = szOID_OIWDIR + ".2";
        public const String szOID_OIWDIR_SIGN                                                                  = szOID_OIWDIR + ".3";
        public const String szOID_OIWDIR_md2                                                                   = szOID_OIWDIR + ".2.1";
        public const String szOID_OIWDIR_md2RSA                                                                = szOID_OIWDIR + ".3.1";
        public const String szOID_INFOSEC                                                                      = "2.16.840.1.101.2.1";
        public const String szOID_INFOSEC_sdnsSignature                                                        = "2.16.840.1.101.2.1.1.1";
        public const String szOID_INFOSEC_mosaicSignature                                                      = "2.16.840.1.101.2.1.1.2";
        public const String szOID_INFOSEC_sdnsConfidentiality                                                  = "2.16.840.1.101.2.1.1.3";
        public const String szOID_INFOSEC_mosaicConfidentiality                                                = "2.16.840.1.101.2.1.1.4";
        public const String szOID_INFOSEC_sdnsIntegrity                                                        = "2.16.840.1.101.2.1.1.5";
        public const String szOID_INFOSEC_mosaicIntegrity                                                      = "2.16.840.1.101.2.1.1.6";
        public const String szOID_INFOSEC_sdnsTokenProtection                                                  = "2.16.840.1.101.2.1.1.7";
        public const String szOID_INFOSEC_mosaicTokenProtection                                                = "2.16.840.1.101.2.1.1.8";
        public const String szOID_INFOSEC_sdnsKeyManagement                                                    = "2.16.840.1.101.2.1.1.9";
        public const String szOID_INFOSEC_mosaicKeyManagement                                                  = "2.16.840.1.101.2.1.1.10";
        public const String szOID_INFOSEC_sdnsKMandSig                                                         = "2.16.840.1.101.2.1.1.11";
        public const String szOID_INFOSEC_mosaicKMandSig                                                       = "2.16.840.1.101.2.1.1.12";
        public const String szOID_INFOSEC_SuiteASignature                                                      = "2.16.840.1.101.2.1.1.13";
        public const String szOID_INFOSEC_SuiteAConfidentiality                                                = "2.16.840.1.101.2.1.1.14";
        public const String szOID_INFOSEC_SuiteAIntegrity                                                      = "2.16.840.1.101.2.1.1.15";
        public const String szOID_INFOSEC_SuiteATokenProtection                                                = "2.16.840.1.101.2.1.1.16";
        public const String szOID_INFOSEC_SuiteAKeyManagement                                                  = "2.16.840.1.101.2.1.1.17";
        public const String szOID_INFOSEC_SuiteAKMandSig                                                       = "2.16.840.1.101.2.1.1.18";
        public const String szOID_INFOSEC_mosaicUpdatedSig                                                     = "2.16.840.1.101.2.1.1.19";
        public const String szOID_INFOSEC_mosaicKMandUpdSig                                                    = "2.16.840.1.101.2.1.1.20";
        public const String szOID_INFOSEC_mosaicUpdatedInteg                                                   = "2.16.840.1.101.2.1.1.21";
        public const String szOID_NIST_sha256                                                                  = "2.16.840.1.101.3.4.2.1";
        public const String szOID_NIST_sha384                                                                  = "2.16.840.1.101.3.4.2.2";
        public const String szOID_NIST_sha512                                                                  = "2.16.840.1.101.3.4.2.3";
        public const String szOID_CP_GOST_PRIVATE_KEYS_V1                                                      = "1.2.643.2.2.37.1";
        public const String szOID_CP_GOST_PRIVATE_KEYS_V2                                                      = "1.2.643.2.2.37.2";
        public const String szOID_CP_GOST_PRIVATE_KEYS_V2_FULL                                                 = "1.2.643.2.2.37.2.1";
        public const String szOID_CP_GOST_PRIVATE_KEYS_V2_PARTOF                                               = "1.2.643.2.2.37.2.2";
        public const String szOID_CP_GOST_R3411                                                                = "1.2.643.2.2.9";
        public const String szOID_CP_GOST_R3411_12_256                                                         = "1.2.643.7.1.1.2.2";
        public const String szOID_CP_GOST_R3411_12_512                                                         = "1.2.643.7.1.1.2.3";
        public const String szOID_CP_GOST_28147                                                                = "1.2.643.2.2.21";
        public const String szOID_CP_GOST_R3412_2015_M                                                         = "1.2.643.7.1.1.5.1";
        public const String szOID_CP_GOST_R3412_2015_K                                                         = "1.2.643.7.1.1.5.2";
        public const String szOID_CP_GOST_R3410                                                                = "1.2.643.2.2.20";
        public const String szOID_CP_GOST_R3410EL                                                              = "1.2.643.2.2.19";
        public const String szOID_CP_GOST_R3410_12_256                                                         = "1.2.643.7.1.1.1.1";
        public const String szOID_CP_GOST_R3410_12_512                                                         = "1.2.643.7.1.1.1.2";
        public const String szOID_CP_DH_EX                                                                     = "1.2.643.2.2.99";
        public const String szOID_CP_DH_EL                                                                     = "1.2.643.2.2.98";
        public const String szOID_CP_DH_12_256                                                                 = "1.2.643.7.1.1.6.1";
        public const String szOID_CP_DH_12_512                                                                 = "1.2.643.7.1.1.6.2";
        public const String szOID_CP_GOST_R3410_94_ESDH                                                        = "1.2.643.2.2.97";
        public const String szOID_CP_GOST_R3410_01_ESDH                                                        = "1.2.643.2.2.96";
        public const String szOID_CP_GOST_R3411_R3410                                                          = "1.2.643.2.2.4";
        public const String szOID_CP_GOST_R3411_R3410EL                                                        = "1.2.643.2.2.3";
        public const String szOID_CP_GOST_R3411_12_256_R3410                                                   = "1.2.643.7.1.1.3.2";
        public const String szOID_CP_GOST_R3411_12_512_R3410                                                   = "1.2.643.7.1.1.3.3";
        public const String szOID_KP_TLS_PROXY                                                                 = "1.2.643.2.2.34.1";
        public const String szOID_KP_RA_CLIENT_AUTH                                                            = "1.2.643.2.2.34.2";
        public const String szOID_KP_WEB_CONTENT_SIGNING                                                       = "1.2.643.2.2.34.3";
        public const String szOID_KP_RA_ADMINISTRATOR                                                          = "1.2.643.2.2.34.4";
        public const String szOID_KP_RA_OPERATOR                                                               = "1.2.643.2.2.34.5";
        public const String szOID_CP_GOST_R3411_94_HMAC                                                        = "1.2.643.2.2.10";
        public const String szOID_CP_GOST_R3411_2012_256_HMAC                                                  = "1.2.643.7.1.1.4.1";
        public const String szOID_CP_GOST_R3411_2012_512_HMAC                                                  = "1.2.643.7.1.1.4.2";
        public const String szOID_OGRN                                                                         = "1.2.643.100.1";
        public const String szOID_OGRNIP                                                                       = "1.2.643.100.5";
        public const String szOID_SNILS                                                                        = "1.2.643.100.3";
        public const String szOID_INN                                                                          = "1.2.643.3.131.1.1";
        public const String szOID_SIGN_TOOL_KC1                                                                = "1.2.643.100.113.1";
        public const String szOID_SIGN_TOOL_KC2                                                                = "1.2.643.100.113.2";
        public const String szOID_SIGN_TOOL_KC3                                                                = "1.2.643.100.113.3";
        public const String szOID_SIGN_TOOL_KB1                                                                = "1.2.643.100.113.4";
        public const String szOID_SIGN_TOOL_KB2                                                                = "1.2.643.100.113.5";
        public const String szOID_SIGN_TOOL_KA1                                                                = "1.2.643.100.113.6";
        public const String szOID_CA_TOOL_KC1                                                                  = "1.2.643.100.114.1";
        public const String szOID_CA_TOOL_KC2                                                                  = "1.2.643.100.114.2";
        public const String szOID_CA_TOOL_KC3                                                                  = "1.2.643.100.114.3";
        public const String szOID_CA_TOOL_KB1                                                                  = "1.2.643.100.114.4";
        public const String szOID_CA_TOOL_KB2                                                                  = "1.2.643.100.114.5";
        public const String szOID_CA_TOOL_KA1                                                                  = "1.2.643.100.114.6";
        public const String szOID_CEP_BASE_PERSONAL                                                            = "1.2.643.2.2.38.1";
        public const String szOID_CEP_BASE_NETWORK                                                             = "1.2.643.2.2.38.2";
        public const String szOID_GostR3411_94_TestParamSet                                                    = "1.2.643.2.2.30.0";
        public const String szOID_GostR3411_94_CryptoProParamSet                                               = "1.2.643.2.2.30.1";	/* ГОСТ Р 34.11-94, параметры по умолчанию */
        public const String szOID_GostR3411_94_CryptoPro_B_ParamSet                                            = "1.2.643.2.2.30.2";
        public const String szOID_GostR3411_94_CryptoPro_C_ParamSet                                            = "1.2.643.2.2.30.3";
        public const String szOID_GostR3411_94_CryptoPro_D_ParamSet                                            = "1.2.643.2.2.30.4";
        public const String szOID_Gost28147_89_TestParamSet                                                    = "1.2.643.2.2.31.0";
        public const String szOID_Gost28147_89_CryptoPro_A_ParamSet                                            = "1.2.643.2.2.31.1";	/* ГОСТ 28147-89, параметры по умолчанию */
        public const String szOID_Gost28147_89_CryptoPro_B_ParamSet                                            = "1.2.643.2.2.31.2";	/* ГОСТ 28147-89, параметры шифрования 1 */
        public const String szOID_Gost28147_89_CryptoPro_C_ParamSet                                            = "1.2.643.2.2.31.3"; 	/* ГОСТ 28147-89, параметры шифрования 2 */
        public const String szOID_Gost28147_89_CryptoPro_D_ParamSet                                            = "1.2.643.2.2.31.4";	/* ГОСТ 28147-89, параметры шифрования 3 */
        public const String szOID_Gost28147_89_CryptoPro_Oscar_1_1_ParamSet                                    = "1.2.643.2.2.31.5";	/* ГОСТ 28147-89, параметры Оскар 1.1 */
        public const String szOID_Gost28147_89_CryptoPro_Oscar_1_0_ParamSet                                    = "1.2.643.2.2.31.6";	/* ГОСТ 28147-89, параметры Оскар 1.0 */
        public const String szOID_Gost28147_89_CryptoPro_RIC_1_ParamSet                                        = "1.2.643.2.2.31.7";	/* ГОСТ 28147-89, параметры РИК 1 */
        public const String szOID_Gost28147_89_TC26_A_ParamSet                                                 = "1.2.643.2.2.31.12";	/* ГОСТ 28147-89, параметры шифрования TC26 2 */
        public const String szOID_Gost28147_89_TC26_B_ParamSet                                                 = "1.2.643.2.2.31.13";	/* ГОСТ 28147-89, параметры шифрования TC26 1 */
        public const String szOID_Gost28147_89_TC26_C_ParamSet                                                 = "1.2.643.2.2.31.14";	/* ГОСТ 28147-89, параметры шифрования TC26 3 */
        public const String szOID_Gost28147_89_TC26_D_ParamSet                                                 = "1.2.643.2.2.31.15";	/* ГОСТ 28147-89, параметры шифрования TC26 4 */
        public const String szOID_Gost28147_89_TC26_E_ParamSet                                                 = "1.2.643.2.2.31.16"; 	/* ГОСТ 28147-89, параметры шифрования TC26 5 */
        public const String szOID_Gost28147_89_TC26_F_ParamSet                                                 = "1.2.643.2.2.31.17";	/* ГОСТ 28147-89, параметры шифрования TC26 6 */
        public const String szOID_Gost28147_89_TC26_Z_ParamSet                                                 = "1.2.643.7.1.2.5.1.1";	/* ГОСТ 28147-89, параметры шифрования ТС26 Z */
        public const String szOID_GostR3410_94_CryptoPro_A_ParamSet                                            = "1.2.643.2.2.32.2"; 	/*VerbaO*/
        public const String szOID_GostR3410_94_CryptoPro_B_ParamSet                                            = "1.2.643.2.2.32.3";
        public const String szOID_GostR3410_94_CryptoPro_C_ParamSet                                            = "1.2.643.2.2.32.4";
        public const String szOID_GostR3410_94_CryptoPro_D_ParamSet                                            = "1.2.643.2.2.32.5";
        public const String szOID_GostR3410_94_TestParamSet                                                    = "1.2.643.2.2.32.0"; 	/*Test*/
        public const String szOID_GostR3410_94_CryptoPro_XchA_ParamSet                                         = "1.2.643.2.2.33.1";
        public const String szOID_GostR3410_94_CryptoPro_XchB_ParamSet                                         = "1.2.643.2.2.33.2";
        public const String szOID_GostR3410_94_CryptoPro_XchC_ParamSet                                         = "1.2.643.2.2.33.3";
        public const String szOID_GostR3410_2001_TestParamSet                                                  = "1.2.643.2.2.35.0";      /* ГОСТ Р 34.10-2001, тестовые параметры */
        public const String szOID_GostR3410_2001_CryptoPro_A_ParamSet                                          = "1.2.643.2.2.35.1";	/* ГОСТ Р 34.10-2001, параметры по умолчанию */
        public const String szOID_GostR3410_2001_CryptoPro_B_ParamSet                                          = "1.2.643.2.2.35.2";	/* ГОСТ Р 34.10-2001, параметры Оскар 2.x */
        public const String szOID_GostR3410_2001_CryptoPro_C_ParamSet                                          = "1.2.643.2.2.35.3";	/* ГОСТ Р 34.10-2001, параметры подписи 1 */
        public const String szOID_tc26_gost_3410_12_256_paramSetA                                              = "1.2.643.7.1.2.1.1.1";	/* ГОСТ Р 34.10-2012, 256 бит, параметры ТК-26, набор A */
        public const String szOID_tc26_gost_3410_12_512_paramSetA                                              = "1.2.643.7.1.2.1.2.1";	/* ГОСТ Р 34.10-2012, 512 бит, параметры по умолчанию */
        public const String szOID_tc26_gost_3410_12_512_paramSetB                                              = "1.2.643.7.1.2.1.2.2";	/* ГОСТ Р 34.10-2012, 512 бит, параметры ТК-26, набор B */
        public const String szOID_tc26_gost_3410_12_512_paramSetC                                              = "1.2.643.7.1.2.1.2.3";	/* ГОСТ Р 34.10-2012, 512 бит, параметры ТК-26, набор С */
        public const String szOID_GostR3410_2001_CryptoPro_XchA_ParamSet                                       = "1.2.643.2.2.36.0";	/* ГОСТ Р 34.10-2001, параметры обмена по умолчанию */
        public const String szOID_GostR3410_2001_CryptoPro_XchB_ParamSet                                       = "1.2.643.2.2.36.1";	/* ГОСТ Р 34.10-2001, параметры обмена 1 */
        public const String szOID_CryptoPro_private_keys_extension_intermediate_store                          = "1.2.643.2.2.37.3.1";
        public const String szOID_CryptoPro_private_keys_extension_signature_trust_store                       = "1.2.643.2.2.37.3.2";
        public const String szOID_CryptoPro_private_keys_extension_exchange_trust_store                        = "1.2.643.2.2.37.3.3";
        public const String szOID_CryptoPro_private_keys_extension_container_friendly_name                     = "1.2.643.2.2.37.3.4";
        public const String szOID_CryptoPro_private_keys_extension_container_key_usage_period                  = "1.2.643.2.2.37.3.5";
        public const String szOID_CryptoPro_private_keys_extension_container_uec_symmetric_key_derive_counter  = "1.2.643.2.2.37.3.6";
        public const String szOID_CryptoPro_private_keys_extension_container_primary_key_properties            = "1.2.643.2.2.37.3.7";
        public const String szOID_CryptoPro_private_keys_extension_container_secondary_key_properties          = "1.2.643.2.2.37.3.8";
        public const String szOID_CryptoPro_private_keys_extension_container_signature_key_usage_period        = "1.2.643.2.2.37.3.9";
        public const String szOID_CryptoPro_private_keys_extension_container_exchange_key_usage_period         = "1.2.643.2.2.37.3.10";
        public const String szOID_CryptoPro_private_keys_extension_container_key_time_validity_control_mode    = "1.2.643.2.2.37.3.11";
        public const String szOID_CryptoPro_extensions_certificate_and_crl_matching_technique                  = "1.2.643.2.2.49.1";
        public const String szCPOID_SubjectSignTool                                                            = "1.2.643.100.111";
        public const String szCPOID_IssuerSignTool                                                             = "1.2.643.100.112";
        public const String szOID_KEY_USAGE = "2.5.29.15";
        }
    }