using System;
using System.Collections.Generic;

namespace BinaryStudio.DirectoryServices
    {
    public class Country
        {
        public String ShortName { get; }
        public String TwoLetterISOCountryName { get; }
        public String ThreeLetterISOCountryName { get; }
        public Int16  Code { get; }
        protected internal Country(String shortname, String two, String three, Int16 code) {
            ShortName = shortname;
            TwoLetterISOCountryName = two;
            ThreeLetterISOCountryName = three;
            Code = code;
            }

        public static readonly IDictionary<String, Country> Countries = new SortedDictionary<String, Country> {
            {"af", new Country("Afghanistan","af","afg",4)},
            {"al", new Country("Albania","al","alb",8)},
            {"aq", new Country("Antarctica","aq","ata",10)},
            {"dz", new Country("Algeria","dz","dza",12)},
            {"as", new Country("American Samoa","as","asm",16)},
            {"ad", new Country("Andorra","ad","and",20)},
            {"ao", new Country("Angola","ao","ago",24)},
            {"ag", new Country("Antigua and Barbuda","ag","atg",28)},
            {"az", new Country("Azerbaijan","az","aze",31)},
            {"ar", new Country("Argentina","ar","arg",32)},
            {"au", new Country("Australia","au","aus",36)},
            {"at", new Country("Austria","at","aut",40)},
            {"bs", new Country("Bahamas","bs","bhs",44)},
            {"bh", new Country("Bahrain","bh","bhr",48)},
            {"bd", new Country("Bangladesh","bd","bgd",50)},
            {"am", new Country("Armenia","am","arm",51)},
            {"bb", new Country("Barbados","bb","brb",52)},
            {"be", new Country("Belgium","be","bel",56)},
            {"bm", new Country("Bermuda","bm","bmu",60)},
            {"bt", new Country("Bhutan","bt","btn",64)},
            {"bo", new Country("Bolivia","bo","bol",68)},
            {"ba", new Country("Bosnia and Herzegovina","ba","bih",70)},
            {"bw", new Country("Botswana","bw","bwa",72)},
            {"bv", new Country("Bouvet Island","bv","bvt",74)},
            {"br", new Country("Brazil","br","bra",76)},
            {"bz", new Country("Belize","bz","blz",84)},
            {"io", new Country("British Indian Ocean Territory","io","iot",86)},
            {"sb", new Country("Solomon Islands","sb","slb",90)},
            {"vg", new Country("Virgin Islands (British)","vg","vgb",92)},
            {"bn", new Country("Brunei Darussalam","bn","brn",96)},
            {"bg", new Country("Bulgaria","bg","bgr",100)},
            {"mm", new Country("Myanmar","mm","mmr",104)},
            {"bi", new Country("Burundi","bi","bdi",108)},
            {"by", new Country("Belarus","by","blr",112)},
            {"kh", new Country("Cambodia","kh","khm",116)},
            {"cm", new Country("Cameroon","cm","cmr",120)},
            {"ca", new Country("Canada","ca","can",124)},
            {"cv", new Country("Cabo Verde","cv","cpv",132)},
            {"ky", new Country("Cayman Islands","ky","cym",136)},
            {"cf", new Country("Central African Republic","cf","caf",140)},
            {"lk", new Country("Sri Lanka","lk","lka",144)},
            {"td", new Country("Chad","td","tcd",148)},
            {"cl", new Country("Chile","cl","chl",152)},
            {"cn", new Country("China","cn","chn",156)},
            {"tw", new Country("Taiwan (Province of China)","tw","twn",158)},
            {"cx", new Country("Christmas Island","cx","cxr",162)},
            {"cc", new Country("Cocos (Keeling) Islands","cc","cck",166)},
            {"co", new Country("Colombia","co","col",170)},
            {"km", new Country("Comoros","km","com",174)},
            {"yt", new Country("Mayotte","yt","myt",175)},
            {"cg", new Country("Congo","cg","cog",178)},
            {"cd", new Country("Congo (the Democratic Republic of the)","cd","cod",180)},
            {"ck", new Country("Cook Islands","ck","cok",184)},
            {"cr", new Country("Costa Rica","cr","cri",188)},
            {"hr", new Country("Croatia","hr","hrv",191)},
            {"cu", new Country("Cuba","cu","cub",192)},
            {"cy", new Country("Cyprus","cy","cyp",196)},
            {"cz", new Country("Czechia","cz","cze",203)},
            {"bj", new Country("Benin","bj","ben",204)},
            {"dk", new Country("Denmark","dk","dnk",208)},
            {"dm", new Country("Dominica","dm","dma",212)},
            {"do", new Country("Dominican Republic","do","dom",214)},
            {"ec", new Country("Ecuador","ec","ecu",218)},
            {"sv", new Country("El Salvador","sv","slv",222)},
            {"gq", new Country("Equatorial Guinea","gq","gnq",226)},
            {"et", new Country("Ethiopia","et","eth",231)},
            {"er", new Country("Eritrea","er","eri",232)},
            {"ee", new Country("Estonia","ee","est",233)},
            {"fo", new Country("Faroe Islands","fo","fro",234)},
            {"fk", new Country("Falkland Islands [Malvinas]","fk","flk",238)},
            {"gs", new Country("South Georgia and the South Sandwich Islands","gs","sgs",239)},
            {"fj", new Country("Fiji","fj","fji",242)},
            {"fi", new Country("Finland","fi","fin",246)},
            {"ax", new Country("Åland Islands","ax","ala",248)},
            {"fr", new Country("France","fr","fra",250)},
            {"gf", new Country("French Guiana","gf","guf",254)},
            {"pf", new Country("French Polynesia","pf","pyf",258)},
            {"tf", new Country("French Southern Territories","tf","atf",260)},
            {"dj", new Country("Djibouti","dj","dji",262)},
            {"ga", new Country("Gabon","ga","gab",266)},
            {"ge", new Country("Georgia","ge","geo",268)},
            {"gm", new Country("Gambia","gm","gmb",270)},
            {"ps", new Country("Palestine, State of","ps","pse",275)},
            {"de", new Country("Germany","de","deu",276)},
            {"gh", new Country("Ghana","gh","gha",288)},
            {"gi", new Country("Gibraltar","gi","gib",292)},
            {"ki", new Country("Kiribati","ki","kir",296)},
            {"gr", new Country("Greece","gr","grc",300)},
            {"gl", new Country("Greenland","gl","grl",304)},
            {"gd", new Country("Grenada","gd","grd",308)},
            {"gp", new Country("Guadeloupe","gp","glp",312)},
            {"gu", new Country("Guam","gu","gum",316)},
            {"gt", new Country("Guatemala","gt","gtm",320)},
            {"gn", new Country("Guinea","gn","gin",324)},
            {"gy", new Country("Guyana","gy","guy",328)},
            {"ht", new Country("Haiti","ht","hti",332)},
            {"hm", new Country("Heard Island and McDonald Islands","hm","hmd",334)},
            {"va", new Country("Holy See","va","vat",336)},
            {"hn", new Country("Honduras","hn","hnd",340)},
            {"hk", new Country("Hong Kong","hk","hkg",344)},
            {"hu", new Country("Hungary","hu","hun",348)},
            {"is", new Country("Iceland","is","isl",352)},
            {"in", new Country("India","in","ind",356)},
            {"id", new Country("Indonesia","id","idn",360)},
            {"ir", new Country("Iran (Islamic Republic of)","ir","irn",364)},
            {"iq", new Country("Iraq","iq","irq",368)},
            {"ie", new Country("Ireland","ie","irl",372)},
            {"il", new Country("Israel","il","isr",376)},
            {"it", new Country("Italy","it","ita",380)},
            {"ci", new Country("Côte d'Ivoire","ci","civ",384)},
            {"jm", new Country("Jamaica","jm","jam",388)},
            {"jp", new Country("Japan","jp","jpn",392)},
            {"kz", new Country("Kazakhstan","kz","kaz",398)},
            {"jo", new Country("Jordan","jo","jor",400)},
            {"ke", new Country("Kenya","ke","ken",404)},
            {"kp", new Country("Korea (the Democratic People's Republic of)","kp","prk",408)},
            {"kr", new Country("Korea (the Republic of)","kr","kor",410)},
            {"kw", new Country("Kuwait","kw","kwt",414)},
            {"kg", new Country("Kyrgyzstan","kg","kgz",417)},
            {"la", new Country("Lao People's Democratic Republic","la","lao",418)},
            {"lb", new Country("Lebanon","lb","lbn",422)},
            {"ls", new Country("Lesotho","ls","lso",426)},
            {"lv", new Country("Latvia","lv","lva",428)},
            {"lr", new Country("Liberia","lr","lbr",430)},
            {"ly", new Country("Libya","ly","lby",434)},
            {"li", new Country("Liechtenstein","li","lie",438)},
            {"lt", new Country("Lithuania","lt","ltu",440)},
            {"lu", new Country("Luxembourg","lu","lux",442)},
            {"mo", new Country("Macao","mo","mac",446)},
            {"mg", new Country("Madagascar","mg","mdg",450)},
            {"mw", new Country("Malawi","mw","mwi",454)},
            {"my", new Country("Malaysia","my","mys",458)},
            {"mv", new Country("Maldives","mv","mdv",462)},
            {"ml", new Country("Mali","ml","mli",466)},
            {"mt", new Country("Malta","mt","mlt",470)},
            {"mq", new Country("Martinique","mq","mtq",474)},
            {"mr", new Country("Mauritania","mr","mrt",478)},
            {"mu", new Country("Mauritius","mu","mus",480)},
            {"mx", new Country("Mexico","mx","mex",484)},
            {"mc", new Country("Monaco","mc","mco",492)},
            {"mn", new Country("Mongolia","mn","mng",496)},
            {"md", new Country("Moldova","md","mda",498)},
            {"me", new Country("Montenegro","me","mne",499)},
            {"ms", new Country("Montserrat","ms","msr",500)},
            {"ma", new Country("Morocco","ma","mar",504)},
            {"mz", new Country("Mozambique","mz","moz",508)},
            {"om", new Country("Oman","om","omn",512)},
            {"na", new Country("Namibia","na","nam",516)},
            {"nr", new Country("Nauru","nr","nru",520)},
            {"np", new Country("Nepal","np","npl",524)},
            {"nl", new Country("Netherlands","nl","nld",528)},
            {"cw", new Country("Curaçao","cw","cuw",531)},
            {"aw", new Country("Aruba","aw","abw",533)},
            {"sx", new Country("Sint Maarten (Dutch part)","sx","sxm",534)},
            {"bq", new Country("Bonaire, Sint Eustatius and Saba","bq","bes",535)},
            {"nc", new Country("New Caledonia","nc","ncl",540)},
            {"vu", new Country("Vanuatu","vu","vut",548)},
            {"nz", new Country("New Zealand","nz","nzl",554)},
            {"ni", new Country("Nicaragua","ni","nic",558)},
            {"ne", new Country("Niger","ne","ner",562)},
            {"ng", new Country("Nigeria","ng","nga",566)},
            {"nu", new Country("Niue","nu","niu",570)},
            {"nf", new Country("Norfolk Island","nf","nfk",574)},
            {"no", new Country("Norway","no","nor",578)},
            {"mp", new Country("Northern Mariana Islands","mp","mnp",580)},
            {"um", new Country("United States Minor Outlying Islands","um","umi",581)},
            {"fm", new Country("Micronesia (Federated States of)","fm","fsm",583)},
            {"mh", new Country("Marshall Islands","mh","mhl",584)},
            {"pw", new Country("Palau","pw","plw",585)},
            {"pk", new Country("Pakistan","pk","pak",586)},
            {"pa", new Country("Panama","pa","pan",591)},
            {"pg", new Country("Papua New Guinea","pg","png",598)},
            {"py", new Country("Paraguay","py","pry",600)},
            {"pe", new Country("Peru","pe","per",604)},
            {"ph", new Country("Philippines","ph","phl",608)},
            {"pn", new Country("Pitcairn","pn","pcn",612)},
            {"pl", new Country("Poland","pl","pol",616)},
            {"pt", new Country("Portugal","pt","prt",620)},
            {"gw", new Country("Guinea-Bissau","gw","gnb",624)},
            {"tl", new Country("Timor-Leste","tl","tls",626)},
            {"pr", new Country("Puerto Rico","pr","pri",630)},
            {"qa", new Country("Qatar","qa","qat",634)},
            {"re", new Country("Réunion","re","reu",638)},
            {"ro", new Country("Romania","ro","rou",642)},
            {"ru", new Country("Russian Federation","ru","rus",643)},
            {"rw", new Country("Rwanda","rw","rwa",646)},
            {"bl", new Country("Saint Barthélemy","bl","blm",652)},
            {"sh", new Country("Saint Helena, Ascension and Tristan da Cunha","sh","shn",654)},
            {"kn", new Country("Saint Kitts and Nevis","kn","kna",659)},
            {"ai", new Country("Anguilla","ai","aia",660)},
            {"lc", new Country("Saint Lucia","lc","lca",662)},
            {"mf", new Country("Saint Martin (French part)","mf","maf",663)},
            {"pm", new Country("Saint Pierre and Miquelon","pm","spm",666)},
            {"vc", new Country("Saint Vincent and the Grenadines","vc","vct",670)},
            {"sm", new Country("San Marino","sm","smr",674)},
            {"st", new Country("Sao Tome and Principe","st","stp",678)},
            {"sa", new Country("Saudi Arabia","sa","sau",682)},
            {"sn", new Country("Senegal","sn","sen",686)},
            {"rs", new Country("Serbia","rs","srb",688)},
            {"sc", new Country("Seychelles","sc","syc",690)},
            {"sl", new Country("Sierra Leone","sl","sle",694)},
            {"sg", new Country("Singapore","sg","sgp",702)},
            {"sk", new Country("Slovakia","sk","svk",703)},
            {"vn", new Country("Viet Nam","vn","vnm",704)},
            {"si", new Country("Slovenia","si","svn",705)},
            {"so", new Country("Somalia","so","som",706)},
            {"za", new Country("South Africa","za","zaf",710)},
            {"zw", new Country("Zimbabwe","zw","zwe",716)},
            {"es", new Country("Spain","es","esp",724)},
            {"ss", new Country("South Sudan","ss","ssd",728)},
            {"sd", new Country("Sudan","sd","sdn",729)},
            {"eh", new Country("Western Sahara","eh","esh",732)},
            {"sr", new Country("Suriname","sr","sur",740)},
            {"sj", new Country("Svalbard and Jan Mayen","sj","sjm",744)},
            {"sz", new Country("Eswatini","sz","swz",748)},
            {"se", new Country("Sweden","se","swe",752)},
            {"ch", new Country("Switzerland","ch","che",756)},
            {"sy", new Country("Syrian Arab Republic","sy","syr",760)},
            {"tj", new Country("Tajikistan","tj","tjk",762)},
            {"th", new Country("Thailand","th","tha",764)},
            {"tg", new Country("Togo","tg","tgo",768)},
            {"tk", new Country("Tokelau","tk","tkl",772)},
            {"to", new Country("Tonga","to","ton",776)},
            {"tt", new Country("Trinidad and Tobago","tt","tto",780)},
            {"ae", new Country("United Arab Emirates","ae","are",784)},
            {"tn", new Country("Tunisia","tn","tun",788)},
            {"tr", new Country("Turkey","tr","tur",792)},
            {"tm", new Country("Turkmenistan","tm","tkm",795)},
            {"tc", new Country("Turks and Caicos Islands","tc","tca",796)},
            {"tv", new Country("Tuvalu","tv","tuv",798)},
            {"ug", new Country("Uganda","ug","uga",800)},
            {"ua", new Country("Ukraine","ua","ukr",804)},
            {"mk", new Country("North Macedonia","mk","mkd",807)},
            {"eg", new Country("Egypt","eg","egy",818)},
            {"gb", new Country("United Kingdom of Great Britain and Northern Ireland","gb","gbr",826)},
            {"gg", new Country("Guernsey","gg","ggy",831)},
            {"je", new Country("Jersey","je","jey",832)},
            {"im", new Country("Isle of Man","im","imn",833)},
            {"tz", new Country("Tanzania, the United Republic of","tz","tza",834)},
            {"us", new Country("United States of America","us","usa",840)},
            {"vi", new Country("Virgin Islands (U.S.)","vi","vir",850)},
            {"bf", new Country("Burkina Faso","bf","bfa",854)},
            {"uy", new Country("Uruguay","uy","ury",858)},
            {"uz", new Country("Uzbekistan","uz","uzb",860)},
            {"ve", new Country("Venezuela (Bolivarian Republic of)","ve","ven",862)},
            {"wf", new Country("Wallis and Futuna","wf","wlf",876)},
            {"ws", new Country("Samoa","ws","wsm",882)},
            {"ye", new Country("Yemen","ye","yem",887)},
            {"zm", new Country("Zambia","zm","zmb",894)},
            };
        }
    }