using System;
using System.Diagnostics.CodeAnalysis;

namespace Internal.CryptoAPICOM
    {
    #if CODE_ANALYSIS
    [SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>")]
    #endif
    public enum CAPICOM_CERTIFICATE_FIND_TYPE
        {
        CAPICOM_CERTIFICATE_FIND_SHA1_HASH,
        CAPICOM_CERTIFICATE_FIND_SUBJECT_NAME,
        CAPICOM_CERTIFICATE_FIND_ISSUER_NAME,
        CAPICOM_CERTIFICATE_FIND_ROOT_NAME,
        CAPICOM_CERTIFICATE_FIND_TEMPLATE_NAME,
        CAPICOM_CERTIFICATE_FIND_EXTENSION,
        CAPICOM_CERTIFICATE_FIND_EXTENDED_PROPERTY,
        CAPICOM_CERTIFICATE_FIND_APPLICATION_POLICY,
        CAPICOM_CERTIFICATE_FIND_CERTIFICATE_POLICY,
        CAPICOM_CERTIFICATE_FIND_TIME_VALID,
        CAPICOM_CERTIFICATE_FIND_TIME_NOT_YET_VALID,
        CAPICOM_CERTIFICATE_FIND_TIME_EXPIRED,
        CAPICOM_CERTIFICATE_FIND_KEY_USAGE
        }
    }
