using System;
using System.Diagnostics.CodeAnalysis;

namespace Internal.CryptoAPICOM
    {
    #if CODE_ANALYSIS
    [SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>")]
    [SuppressMessage("Naming", "CA1712:Do not prefix enum values with type name", Justification = "<Pending>")]
    [SuppressMessage("Design", "CA1069:Enums values should not be duplicated", Justification = "<Pending>")]
    #endif
    public enum CAPICOM_PROPID
        {
        CAPICOM_PROPID_UNKNOWN,
        CAPICOM_PROPID_KEY_PROV_HANDLE,
        CAPICOM_PROPID_KEY_PROV_INFO,
        CAPICOM_PROPID_SHA1_HASH,
        CAPICOM_PROPID_HASH_PROP = 3,
        CAPICOM_PROPID_MD5_HASH,
        CAPICOM_PROPID_KEY_CONTEXT,
        CAPICOM_PROPID_KEY_SPEC,
        CAPICOM_PROPID_IE30_RESERVED,
        CAPICOM_PROPID_PUBKEY_HASH_RESERVED,
        CAPICOM_PROPID_ENHKEY_USAGE,
        CAPICOM_PROPID_CTL_USAGE = 9,
        CAPICOM_PROPID_NEXT_UPDATE_LOCATION,
        CAPICOM_PROPID_FRIENDLY_NAME,
        CAPICOM_PROPID_PVK_FILE,
        CAPICOM_PROPID_DESCRIPTION,
        CAPICOM_PROPID_ACCESS_STATE,
        CAPICOM_PROPID_SIGNATURE_HASH,
        CAPICOM_PROPID_SMART_CARD_DATA,
        CAPICOM_PROPID_EFS,
        CAPICOM_PROPID_FORTEZZA_DATA,
        CAPICOM_PROPID_ARCHIVED,
        CAPICOM_PROPID_KEY_IDENTIFIER,
        CAPICOM_PROPID_AUTO_ENROLL,
        CAPICOM_PROPID_PUBKEY_ALG_PARA,
        CAPICOM_PROPID_CROSS_CERT_DIST_POINTS,
        CAPICOM_PROPID_ISSUER_PUBLIC_KEY_MD5_HASH,
        CAPICOM_PROPID_SUBJECT_PUBLIC_KEY_MD5_HASH,
        CAPICOM_PROPID_ENROLLMENT,
        CAPICOM_PROPID_DATE_STAMP,
        CAPICOM_PROPID_ISSUER_SERIAL_NUMBER_MD5_HASH,
        CAPICOM_PROPID_SUBJECT_NAME_MD5_HASH,
        CAPICOM_PROPID_EXTENDED_ERROR_INFO,
        CAPICOM_PROPID_RENEWAL = 64,
        CAPICOM_PROPID_ARCHIVED_KEY_HASH,
        CAPICOM_PROPID_FIRST_RESERVED,
        CAPICOM_PROPID_LAST_RESERVED = 32767,
        CAPICOM_PROPID_FIRST_USER,
        CAPICOM_PROPID_LAST_USER = 65535
        }
    }
