using System;
using System.Diagnostics.CodeAnalysis;

namespace Internal.CryptoAPICOM
    {
    #if CODE_ANALYSIS
    [SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>")]
    #endif
    public enum CAPICOM_ERROR_CODE
        {
        CAPICOM_E_ENCODE_INVALID_TYPE = -2138570496,
        CAPICOM_E_EKU_INVALID_OID = -2138570240,
        CAPICOM_E_EKU_OID_NOT_INITIALIZED,
        CAPICOM_E_CERTIFICATE_NOT_INITIALIZED = -2138570224,
        CAPICOM_E_CERTIFICATE_NO_PRIVATE_KEY,
        CAPICOM_E_CHAIN_NOT_BUILT = -2138570208,
        CAPICOM_E_STORE_NOT_OPENED = -2138570192,
        CAPICOM_E_STORE_EMPTY,
        CAPICOM_E_STORE_INVALID_OPEN_MODE,
        CAPICOM_E_STORE_INVALID_SAVE_AS_TYPE,
        CAPICOM_E_ATTRIBUTE_NAME_NOT_INITIALIZED = -2138570176,
        CAPICOM_E_ATTRIBUTE_VALUE_NOT_INITIALIZED,
        CAPICOM_E_ATTRIBUTE_INVALID_NAME,
        CAPICOM_E_ATTRIBUTE_INVALID_VALUE,
        CAPICOM_E_SIGNER_NOT_INITIALIZED = -2138570160,
        CAPICOM_E_SIGNER_NOT_FOUND,
        CAPICOM_E_SIGNER_NO_CHAIN,
        CAPICOM_E_SIGNER_INVALID_USAGE,
        CAPICOM_E_SIGN_NOT_INITIALIZED = -2138570144,
        CAPICOM_E_SIGN_INVALID_TYPE,
        CAPICOM_E_SIGN_NOT_SIGNED,
        CAPICOM_E_INVALID_ALGORITHM = -2138570128,
        CAPICOM_E_INVALID_KEY_LENGTH,
        CAPICOM_E_ENVELOP_NOT_INITIALIZED = -2138570112,
        CAPICOM_E_ENVELOP_INVALID_TYPE,
        CAPICOM_E_ENVELOP_NO_RECIPIENT,
        CAPICOM_E_ENVELOP_RECIPIENT_NOT_FOUND,
        CAPICOM_E_ENCRYPT_NOT_INITIALIZED = -2138570096,
        CAPICOM_E_ENCRYPT_INVALID_TYPE,
        CAPICOM_E_ENCRYPT_NO_SECRET,
        CAPICOM_E_NOT_SUPPORTED = -2138568448,
        CAPICOM_E_UI_DISABLED,
        CAPICOM_E_CANCELLED,
        CAPICOM_E_NOT_ALLOWED,
        CAPICOM_E_OUT_OF_RESOURCE,
        CAPICOM_E_INTERNAL = -2138568431,
        CAPICOM_E_UNKNOWN = -2138568295,
        CAPICOM_E_PRIVATE_KEY_NOT_INITIALIZED = -2138569984,
        CAPICOM_E_PRIVATE_KEY_NOT_EXPORTABLE,
        CAPICOM_E_ENCODE_NOT_INITIALIZED = -2138569952,
        CAPICOM_E_EXTENSION_NOT_INITIALIZED = -2138569936,
        CAPICOM_E_PROPERTY_NOT_INITIALIZED = -2138569920,
        CAPICOM_E_FIND_INVALID_TYPE = -2138569904,
        CAPICOM_E_FIND_INVALID_PREDEFINED_POLICY,
        CAPICOM_E_CODE_NOT_INITIALIZED = -2138569888,
        CAPICOM_E_CODE_NOT_SIGNED,
        CAPICOM_E_CODE_DESCRIPTION_NOT_INITIALIZED,
        CAPICOM_E_CODE_DESCRIPTION_URL_NOT_INITIALIZED,
        CAPICOM_E_CODE_INVALID_TIMESTAMP_URL,
        CAPICOM_E_HASH_NO_DATA = -2138569872,
        CAPICOM_E_INVALID_CONVERT_TYPE = -2138569856
        }
    }
