using System;

namespace Microsoft.Win32
    {
    [Flags]
    public enum CERT_CHAIN_POLICY_FLAGS
        {
        CERT_CHAIN_POLICY_IGNORE_NOT_TIME_VALID_FLAG                 = 0x00000001,
        CERT_CHAIN_POLICY_IGNORE_CTL_NOT_TIME_VALID_FLAG             = 0x00000002,
        CERT_CHAIN_POLICY_IGNORE_NOT_TIME_NESTED_FLAG                = 0x00000004,
        CERT_CHAIN_POLICY_IGNORE_INVALID_BASIC_CONSTRAINTS_FLAG      = 0x00000008,
        CERT_CHAIN_POLICY_IGNORE_ALL_NOT_TIME_VALID_FLAGS            =
            CERT_CHAIN_POLICY_IGNORE_NOT_TIME_VALID_FLAG          |
            CERT_CHAIN_POLICY_IGNORE_CTL_NOT_TIME_VALID_FLAG      |
            CERT_CHAIN_POLICY_IGNORE_NOT_TIME_NESTED_FLAG,
        CERT_CHAIN_POLICY_ALLOW_UNKNOWN_CA_FLAG                      = 0x00000010,
        CERT_CHAIN_POLICY_IGNORE_WRONG_USAGE_FLAG                    = 0x00000020,
        CERT_CHAIN_POLICY_IGNORE_INVALID_NAME_FLAG                   = 0x00000040,
        CERT_CHAIN_POLICY_IGNORE_INVALID_POLICY_FLAG                 = 0x00000080,
        CERT_CHAIN_POLICY_IGNORE_END_REV_UNKNOWN_FLAG                = 0x00000100,
        CERT_CHAIN_POLICY_IGNORE_CTL_SIGNER_REV_UNKNOWN_FLAG         = 0x00000200,
        CERT_CHAIN_POLICY_IGNORE_CA_REV_UNKNOWN_FLAG                 = 0x00000400,
        CERT_CHAIN_POLICY_IGNORE_ROOT_REV_UNKNOWN_FLAG               = 0x00000800,
        CERT_CHAIN_POLICY_IGNORE_ALL_REV_UNKNOWN_FLAGS               =
            CERT_CHAIN_POLICY_IGNORE_END_REV_UNKNOWN_FLAG         |
            CERT_CHAIN_POLICY_IGNORE_CTL_SIGNER_REV_UNKNOWN_FLAG  |
            CERT_CHAIN_POLICY_IGNORE_CA_REV_UNKNOWN_FLAG          |
            CERT_CHAIN_POLICY_IGNORE_ROOT_REV_UNKNOWN_FLAG,
        CERT_CHAIN_POLICY_ALLOW_TESTROOT_FLAG                        = 0x00008000,
        CERT_CHAIN_POLICY_TRUST_TESTROOT_FLAG                        = 0x00004000,
        CERT_CHAIN_POLICY_IGNORE_NOT_SUPPORTED_CRITICAL_EXT_FLAG     = 0x00002000,
        CERT_CHAIN_POLICY_IGNORE_PEER_TRUST_FLAG                     = 0x00001000,
        CERT_CHAIN_POLICY_IGNORE_WEAK_SIGNATURE_FLAG                 = 0x08000000,
        BASIC_CONSTRAINTS_CERT_CHAIN_POLICY_CA_FLAG                  = unchecked((Int32)0x80000000),
        BASIC_CONSTRAINTS_CERT_CHAIN_POLICY_END_ENTITY_FLAG          = 0x40000000,
        MICROSOFT_ROOT_CERT_CHAIN_POLICY_ENABLE_TEST_ROOT_FLAG       = 0x00010000,
        MICROSOFT_ROOT_CERT_CHAIN_POLICY_CHECK_APPLICATION_ROOT_FLAG = 0x00020000,
        MICROSOFT_ROOT_CERT_CHAIN_POLICY_DISABLE_FLIGHT_ROOT_FLAG    = 0x00040000
        }
    }