namespace Microsoft.Win32
    {
    public enum CRYPT_PARAM : uint
        {
        PP_ENUMALGS             =  1,
        PP_ENUMCONTAINERS       =  2,
        PP_IMPTYPE              =  3,
        PP_NAME                 =  4,
        PP_VERSION              =  5,
        PP_CONTAINER            =  6,
        PP_CHANGE_PASSWORD      =  7,
        PP_KEYSET_SEC_DESCR     =  8,
        PP_CERTCHAIN            =  9,
        PP_KEY_TYPE_SUBTYPE     = 10,
        PP_PROVTYPE             = 16,
        PP_KEYSTORAGE           = 17,
        PP_APPLI_CERT           = 18,
        PP_SYM_KEYSIZE          = 19,
        PP_SESSION_KEYSIZE      = 20,
        PP_UI_PROMPT            = 21,
        PP_ENUMALGS_EX          = 22,
        PP_ENUMMANDROOTS        = 25,
        PP_ENUMELECTROOTS       = 26,
        PP_KEYSET_TYPE          = 27,
        PP_ADMIN_PIN            = 31,
        PP_KEYEXCHANGE_PIN      = 32,
        PP_SIGNATURE_PIN        = 33,
        PP_SIG_KEYSIZE_INC      = 34,
        PP_KEYX_KEYSIZE_INC     = 35,
        PP_UNIQUE_CONTAINER     = 36,
        PP_SGC_INFO             = 37,
        PP_USE_HARDWARE_RNG     = 38,
        PP_KEYSPEC              = 39,
        PP_ENUMEX_SIGNING_PROT  = 40,
        PP_CRYPT_COUNT_KEY_USE  = 41,
        PP_USER_CERTSTORE       = 42,
        PP_SMARTCARD_READER     = 43,
        PP_SMARTCARD_GUID       = 45,
        PP_ROOT_CERTSTORE       = 46,
        PP_PIN_PROMPT_STRING      = 44,
        PP_SECURE_KEYEXCHANGE_PIN = 47,
        PP_SECURE_SIGNATURE_PIN   = 48,
        PP_FQCN                 = 111,
        PP_PIN_INFO             = 120
        }
    }