namespace BinaryStudio.PortableExecutable.Win32
    {
    public enum CV_TRI
        {
        CV_TRI_NOREG    =   0,

        // General Purpose Data Registers

        CV_TRI_D0   =   10,
        CV_TRI_D1   =   11,
        CV_TRI_D2   =   12,
        CV_TRI_D3   =   13,
        CV_TRI_D4   =   14,
        CV_TRI_D5   =   15,
        CV_TRI_D6   =   16,
        CV_TRI_D7   =   17,
        CV_TRI_D8   =   18,
        CV_TRI_D9   =   19,
        CV_TRI_D10  =   20,
        CV_TRI_D11  =   21,
        CV_TRI_D12  =   22,
        CV_TRI_D13  =   23,
        CV_TRI_D14  =   24,
        CV_TRI_D15  =   25,

        // General Purpose Address Registers

        CV_TRI_A0   =   26,
        CV_TRI_A1   =   27,
        CV_TRI_A2   =   28,
        CV_TRI_A3   =   29,
        CV_TRI_A4   =   30,
        CV_TRI_A5   =   31,
        CV_TRI_A6   =   32,
        CV_TRI_A7   =   33,
        CV_TRI_A8   =   34,
        CV_TRI_A9   =   35,
        CV_TRI_A10  =   36,
        CV_TRI_A11  =   37,
        CV_TRI_A12  =   38,
        CV_TRI_A13  =   39,
        CV_TRI_A14  =   40,
        CV_TRI_A15  =   41,

        // Extended (64-bit) data registers

        CV_TRI_E0   =   42,
        CV_TRI_E2   =   43,
        CV_TRI_E4   =   44,
        CV_TRI_E6   =   45,
        CV_TRI_E8   =   46,
        CV_TRI_E10  =   47,
        CV_TRI_E12  =   48,
        CV_TRI_E14  =   49,

        // Extended (64-bit) address registers

        CV_TRI_EA0  =   50,
        CV_TRI_EA2  =   51,
        CV_TRI_EA4  =   52,
        CV_TRI_EA6  =   53,
        CV_TRI_EA8  =   54,
        CV_TRI_EA10 =   55,
        CV_TRI_EA12 =   56,
        CV_TRI_EA14 =   57,

        CV_TRI_PSW  =   58,
        CV_TRI_PCXI =   59,
        CV_TRI_PC   =   60,
        CV_TRI_FCX  =   61,
        CV_TRI_LCX  =   62,
        CV_TRI_ISP  =   63,
        CV_TRI_ICR  =   64,
        CV_TRI_BIV  =   65,
        CV_TRI_BTV  =   66,
        CV_TRI_SYSCON   =   67,
        CV_TRI_DPRx_0   =   68,
        CV_TRI_DPRx_1   =   69,
        CV_TRI_DPRx_2   =   70,
        CV_TRI_DPRx_3   =   71,
        CV_TRI_CPRx_0   =   68,
        CV_TRI_CPRx_1   =   69,
        CV_TRI_CPRx_2   =   70,
        CV_TRI_CPRx_3   =   71,
        CV_TRI_DPMx_0   =   68,
        CV_TRI_DPMx_1   =   69,
        CV_TRI_DPMx_2   =   70,
        CV_TRI_DPMx_3   =   71,
        CV_TRI_CPMx_0   =   68,
        CV_TRI_CPMx_1   =   69,
        CV_TRI_CPMx_2   =   70,
        CV_TRI_CPMx_3   =   71,
        CV_TRI_DBGSSR   =   72,
        CV_TRI_EXEVT    =   73,
        CV_TRI_SWEVT    =   74,
        CV_TRI_CREVT    =   75,
        CV_TRI_TRnEVT   =   76,
        CV_TRI_MMUCON   =   77,
        CV_TRI_ASI      =   78,
        CV_TRI_TVA      =   79,
        CV_TRI_TPA      =   80,
        CV_TRI_TPX      =   81,
        CV_TRI_TFA      =   82,
        }
    }